CMSys/CMSys.Web/ViewModels/CoursesViewModel.cs
using System.Collections.Generic;
using CMSys.Core.Entities.Catalog;

namespace CMSys.Web.ViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<Course> Courses { get; set; }

        public PageViewModel PageViewModel { get; set; }

        public CoursesViewModel(IEnumerable<Course> courses, PageViewModel pageViewModel)
        {
            Courses = courses;
            PageViewModel = pageViewModel;
        }
    }
}

CMSys/CMSys.Web/ViewModels/PageViewModel.cs
using System;

namespace CMSys.Web.ViewModels
{
    public class PageViewModel
    {
        public int PageNumber { get; set; }

        public int TotalPages { get; set; }

        public int PageSize { get; set; }

        public bool HasPreviousPage => (PageNumber > 1);

        public bool HasNextPage => (PageNumber < TotalPages);

        public PageViewModel(int totalEntries, int pageNumber, int pageSize)
        {
            PageNumber = pageNumber;
            PageSize = pageSize;

            TotalPages = (int) Math.Ceiling((double) totalEntries / PageSize);
        }
    }
}

CMSys/CMSys.Web/ViewModels/TrainerGroupViewModel.cs
using System.Collections.Generic;
using System.Linq;
using CMSys.Core.Entities.Catalog;

namespace CMSys.Web.ViewModels
{
    public class TrainerGroupViewModel
    {
        public TrainerGroup Group { get; set; }

        public List<Trainer> Trainers { get; set; }

        public TrainerGroupViewModel(IGrouping<TrainerGroup, Trainer> group)
        {
            Group = group.Key;
            Trainers = group.ToList();
        }
    }
}

CMSys/CMSys.Web/Controllers/CoursesController.cs
using System.Linq;
using CMSys.Core.Repositories;
using CMSys.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CMSys.Web.Controllers
{
    //[Route("[controller]")]
    public class CoursesController : Controller
    {
        private readonly ILogger<TrainersController> _logger;

        private readonly IUnitOfWork _unitOfWork;

        public CoursesController(ILogger<TrainersController> logger,
            IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        [Route("")]
        [Route("[action]")]
        public IActionResult Courses(int pageNumber = 1)
        {
            var courses = _unitOfWork.CourseRepository.All();
            var pageViewModel = new PageViewModel(courses.Count(), pageNumber, 5);
            var courseViewModel = new CoursesViewModel(courses, pageViewModel);

            return View(courseViewModel);
        }

        [Route("[action]")]
        public IActionResult CoursesList()
        {
            return View();
        }

        [Route("action")]
        public IActionResult CourseGroups()
        {
            return View();
        }
    }
}

CMSys/CMSys.Web/Controllers/TrainersController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CMSys.Core.Repositories;
using CMSys.Web.ViewModels;

namespace CMSys.Web.Controllers
{
    [Route("[controller]")]
    public class TrainersController : Controller
    {
        private readonly ILogger<TrainersController> _logger;

        private readonly IUnitOfWork _unitOfWork;

        public TrainersController(ILogger<TrainersController> logger,
            IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        [Route("[action]")]
        public IActionResult Trainers()
        {
            var groups = _unitOfWork.TrainerRepository
                .All()
                .GroupBy(trainer => trainer.TrainerGroup)
                .Select(group => new TrainerGroupViewModel(group));

            return View(groups);
        }

        [Route("[action]")]
        public IActionResult TrainersList()
        {
            return View();
        }

        [Route("[action]")]
        public IActionResult TrainerGroups()
        {
            return View();
        }
    }
}

CMSys/CMSys.Web/Controllers/UsersController.cs
using CMSys.Core.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CMSys.Web.Controllers
{
    [Route("[controller]")]
    public class UsersController : Controller
    {
        private readonly ILogger<TrainersController> _logger;

        private readonly IUnitOfWork _unitOfWork;

        public UsersController(ILogger<TrainersController> logger,
            IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }

        [Route("[action]")]
        public IActionResult Users()
        {
            return View();
        }
    }
}

CMSys/CMSys.Web/Views/Courses/CourseGroups.cshtml
@{
    ViewData["Title"] = "Course Group";
}

CMSys/CMSys.Web/Views/Courses/Courses.cshtml
@model CoursesViewModel
@{
    ViewData["Title"] = "Courses";
}

<div class="flex-row-reverse">
    <select class="form-select">
        <option value="All">All Types</option>
    </select>
    <select class="form-select">
        <option value="All">All Courses</option>
    </select>
</div>

@foreach (Course course in Model.Courses)
{
    <div class="card">
        <div class="card-body">
            <h2>@course.Name</h2>
        </div>
    </div>
}

CMSys/CMSys.Web/Views/Courses/CoursesList.cshtml
@{
    ViewData["Title"] = "Course List";
}

CMSys/CMSys.Web/Views/Shared/_Main.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - CMSys.Web</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-primary sidebar">
                <div class="sidebar-sticky">
                    <h4 class="sidebar-heading">CMSYS</h4>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Courses" asp-action="Courses">
                                <i class="fas fa-laptop-code"></i>
                                Courses
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Trainers" asp-action="Trainers">
                                <i class="fas fa-chalkboard-teacher"></i>
                                Trainers
                            </a>
                        </li>
                    </ul>
                    <hr class="nav hr"/>
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Courses" asp-action="CoursesList">
                                <i class="fas fa-list-ul"></i>
                                Course List
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Courses" asp-action="CourseGroups">
                                <i class="far fa-window-restore"></i>
                                Course Groups
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Trainers" asp-action="TrainersList">
                                <i class="far fa-address-card"></i>
                                Trainer List
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Trainers" asp-action="TrainerGroups">
                                <i class="fas fa-users"></i>
                                Trainer Groups
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Users" asp-action="Users">
                                <i class="fas fa-user-friends"></i>
                                Users
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10">
        <header>
            <nav class="navbar navbar-light box-shadow">
                <div class="container">
                    <div class="navbar">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark">Login</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <div class="pb-3">
                <h3 class="page-header">@ViewData["Title"]</h3>
                @RenderBody()
            </div>
        </div>
    </main>
    
    <script src="https://kit.fontawesome.com/d2c493077c.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CMSys/CMSys.Web/Views/Trainers/TrainerGroups.cshtml
@{
    ViewData["Title"] = "Trainer Groups";
}

CMSys/CMSys.Web/Views/Trainers/TrainerInfoPartial.cshtml
@model Trainer
@{
    string img64 = Convert.ToBase64String(Model.User.Photo);
    string elementId = $"user{Model.Id}";
}

<div id="@elementId" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@Model.User.FullName</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-auto">
                        <img src="@($"data:image/png;base64,{img64}")" alt="@Model.User.FirstName"/>
                    </div>
                    <div class="col">
                        <label>@Model.Description</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CMSys/CMSys.Web/Views/Trainers/Trainers.cshtml
@model IEnumerable<TrainerGroupViewModel>
@{
    ViewData["Title"] = "Trainers";
}

@foreach (TrainerGroupViewModel group in @Model)
{
    <div class="card shadow-sm">
        <div class="card-header">
            <b>@group.Group.Name</b>
        </div>
        <div class="card-body">
            <div class="row">
                @foreach (Trainer trainer in group.Trainers)
                {
                    string img64 = Convert.ToBase64String(trainer.User.Photo);
                    string elementId = $"user{trainer.Id}";

                    <div class="col-2">
                        <img src="@($"data:image/png;base64,{img64}")" alt="@trainer.User.FirstName" /><br />
                        <small>@trainer.User.FullName</small>
                        <a href="#@elementId" data-toggle="modal">
                            <i class="fas fa-info-circle"></i>
                        </a>
                    </div>

                    <partial name="TrainerInfoPartial" model="@trainer" />
                }
            </div>
        </div>
    </div>
}

CMSys/CMSys.Web/Views/Trainers/TrainersList.cshtml
@{
    ViewData["Title"] = "Trainer List";
}

CMSys/CMSys.Web/Views/Users/Users.cshtml
@{
    ViewData["Title"] = "Users";
}